### ISSUE TITLE
License

### ISSUE THREAD

**Issue by her001** [rjtwins/MW5-Mod-Manager#3]
Hello,

I was thinking of contributing to this project, but I did not notice any indication of the license that this code is released under.

1. What was your intention for this project?
1. Do you want to give this an open source license?

If you aren't sure, perhaps I can help explain some of the options (though I am not a lawyer).

Thanks!

**Comment by rjtwins** [comment]
I just put up GNU GENERAL PUBLIC LICENSE Version 3 so you may do with this whatever you like as long as the source is openly available.

**Comment by her001** [comment]
Excellent, thank you!
